{{- define "sock-shop.orders.svc" -}}
metadata:
  name: orders
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: orders
{{- end -}}
{{- include "sock-shop.svc" (list . "sock-shop.orders.svc" ) }}
