{{- define "sock-shop.payment.svc" -}}
metadata:
  name: payment
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: payment
{{- end -}}
{{- include "sock-shop.svc" (list . "sock-shop.payment.svc" ) }}
