{{- define "sock-shop.queue-master.svc" -}}
metadata:
  name: queue-master
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: queue-master
{{- end -}}
{{- include "sock-shop.svc" (list . "sock-shop.queue-master.svc" ) }}
