{{- define "sock-shop.catalogue-db.hpa" -}}
metadata:
  name: catalogue-db
spec:
  scaleTargetRef:
    name: catalogue-db
{{- end -}}
{{- include "sock-shop.hpa" (list . "sock-shop.catalogue-db.hpa" ) }}
