{{- define "sock-shop.user-db.svc" -}}
metadata:
  name: user-db
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: user-db
{{- end -}}
{{- include "sock-shop.svc" (list . "sock-shop.user-db.svc" ) }}
