{{- define "sock-shop.queue-master.hpa" -}}
metadata:
  name: queue-master
spec:
  scaleTargetRef:
    name: queue-master
{{- end -}}
{{- include "sock-shop.hpa" (list . "sock-shop.queue-master.hpa" ) }}
