name: EKS Cost predict 3
permissions:
  id-token: write
  contents: write
  pull-requests: write
on:
  pull_request:
    branches: ["dev", "master"]
    types: [opened, reopened, synchronize]
    paths:
    - 'helm-chart/sock-shop/values/**/values.yaml'

jobs:
  eks-cost-predict:
    environment: dev #${{ matrix.environment }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # - name: Clone Module Repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: devops-sangwon/gh-module
      #     ref: ${{ secrets.module_version }}
      #     path: ./action_modules
      # - name: Get AWS Credentials 
      #   uses: ./action_modules/common/aws/credential
      #   with:
      #     AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      # - name: setup kubectl & helm
      #   uses: ./action_modules/common/deploy/helm
      #   with:
      #     EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}
      - name: detect helm chart values file
        run: |
          echo "Update working-directory in helm-chart"
      - name: timestamp
        id: time
        run: |
          TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
          echo $TIMESTAMP
          echo $TIMESTAMP > template.md
          echo "Cat template.md"
          cat template.md
          echo "Move"
          mv template.md $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          echo "Cat workspace/template.md"
          cat $GITHUB_WORKSPACE/template.md
      - uses: mshick/add-pr-comment@v2
        with:
          message-path: $GITHUB_WORKSPACE/.template.md
      