name: chatbot On EKS
on:
  repository_dispatch:
    types: [run]
jobs:
  chatbot-eks-on:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment: ["${{ github.event.client_payload.deploy_env }}"]
    steps:
      - name: Clone Module Repository
        uses: actions/checkout@v3
        with:
          repository: devops-sangwon/gh-module
          ref: ${{ secrets.module_version }}
          path: ./action_modules
      - uses: actions/checkout@v3
      - name: Get AWS Credentials 
        uses: ./action_modules/common/aws/credential
        with:
          AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      - name: setup kubectl & helm
        uses: ./action_modules/common/deploy/helm
        with:
          EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}
      - name: Helm Rollback history
        run: |
          REVISION=`helm history ${{ github.event.client_payload.helm }} -n ${{ github.event.client_payload.namespace }} | xargs`
          REVISION=$((REVISION))
          LAST_REVISION=$(($REVISION -1))
          helm rollback ${{ github.event.client_payload.helm }} $LAST_REVISION -n ${{ github.event.client_payload.namespace }}

  slack:
    runs-on: ubuntu-22.04
    needs: [chatbot-eks-on]
    if: always()
    steps:
      - name: Clone Module Repository
        uses: actions/checkout@v3
        with:
          repository: devops-sangwon/gh-module
          ref: ${{ secrets.module_version }}
          path: ./action_modules
      - name: Send to Slack (Success)
        if: |
          needs.chatbot-eks-on.result == 'success'
        uses: ./action_modules/common/slack/success/eks-cost-project/chatbot
        with:
          MESSAGE: 'Success EKS CLUSTER'
          TYPE: ${{ github.event.client_payload.type }}
          EKS_CLUSTER: ${{ github.event.client_payload.eks_cluster }}
          TARGET_NAMESPACE: ${{ github.event.client_payload.namespace }}
          TARGET_HELM: ${{ github.event.client_payload.helm }}
          SLACK_WEBHOOK: ${{ secrets.CHATOPS_SLACK_WEBHOOK }}
      - name: Send to Slack(Failure)
        if: |
          needs.chatbot-eks-on.result == 'failure'
        uses: ./action_modules/common/slack/failure/eks-cost-project/chatbot
        with:
          MESSAGE: 'Failure EKS CLUSTER'
          TYPE: ${{ github.event.client_payload.type }}
          EKS_CLUSTER: ${{ github.event.client_payload.eks_cluster }}
          TARGET_NAMESPACE: ${{ github.event.client_payload.namespace }}
          TARGET_HELM: ${{ github.event.client_payload.helm }}
          SLACK_WEBHOOK: ${{ secrets.CHATOPS_SLACK_WEBHOOK }}