{{- define "sock-shop.hpa.tpl" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sock-shop.fullname" . }}
  labels:
    {{- include "sock-shop.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sock-shop.fullname" . }}
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
{{- end }}

{{- define "sock-shop.hpa" -}}
{{- include "sock-shop.util.merge" (append . "sock-shop.hpa.tpl") -}}
{{- end -}}